# Generated by Django 6.0.2 on 2026-02-04 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('campaign_type', models.CharField(choices=[('jojo', 'JoJo Bizarre Adventure'), ('jjk', 'Jujutsu Kaisen'), ('bleach', 'Bleach'), ('generic', 'FATE Genérico')], default='generic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaign_images/')),
                ('era_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('location_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('projection_image', models.ImageField(blank=True, null=True, upload_to='projections/')),
                ('projection_title', models.CharField(blank=True, default='', max_length=200)),
                ('projection_updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status_type', models.CharField(blank=True, default='', max_length=100)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('use_status', models.CharField(blank=True, default='', max_length=50)),
                ('damage_base', models.CharField(default='0', max_length=100)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fate_points', models.IntegerField(default=3)),
                ('forca', models.IntegerField(default=0, verbose_name='Força')),
                ('destreza', models.IntegerField(default=0, verbose_name='Destreza')),
                ('vigor', models.IntegerField(default=0, verbose_name='Vigor')),
                ('inteligencia', models.IntegerField(default=0, verbose_name='Inteligência')),
                ('sabedoria', models.IntegerField(default=0, verbose_name='Sabedoria')),
                ('carisma', models.IntegerField(default=0, verbose_name='Carisma')),
                ('hierarchy', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('is_npc', models.BooleanField(default=False)),
                ('abilities', models.ManyToManyField(blank=True, to='api.ability')),
                ('advantages', models.ManyToManyField(blank=True, to='api.advantage')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='api.campaign')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.character')),
            ],
        ),
        migrations.CreateModel(
            name='CursedTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('technique_type', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='technique_images/')),
                ('cursed_energy_cost', models.IntegerField(default=0)),
                ('damage_base', models.CharField(default='0', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('abilities', models.ManyToManyField(blank=True, to='api.ability')),
                ('owner_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursed_techniques', to='api.character')),
            ],
        ),
        migrations.CreateModel(
            name='DiceRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_1', models.IntegerField()),
                ('dice_2', models.IntegerField()),
                ('dice_3', models.IntegerField()),
                ('dice_4', models.IntegerField()),
                ('dice_total', models.IntegerField()),
                ('used_fate_point', models.BooleanField(default=False)),
                ('final_total', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('hidden_bonus', models.IntegerField(default=0)),
                ('hidden_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_by_master', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_rolls', to='api.campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_rolls', to='api.character')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('item_type', models.CharField(choices=[('weapon', 'Arma'), ('armor', 'Armadura'), ('consumable', 'Consumível'), ('accessory', 'Acessório'), ('quest', 'Item de Quest'), ('misc', 'Diversos')], default='misc', max_length=20)),
                ('durability', models.IntegerField(default=100)),
                ('is_equipped', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('bonus_status', models.CharField(blank=True, default='', max_length=50)),
                ('bonus_value', models.IntegerField(default=0)),
                ('owner_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.character')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_sent', to='api.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='api.item')),
                ('to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to='api.character')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('trade', 'Troca de Item'), ('roll', 'Rolagem de Dados'), ('fate', 'Uso de Fate Point'), ('system', 'Sistema')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.campaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.character')),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.item')),
                ('related_roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.diceroll')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('use_status', models.CharField(blank=True, default='', max_length=50)),
                ('bonus', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personality_traits', to='api.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='personality_traits',
            field=models.ManyToManyField(blank=True, to='api.personalitytrait'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_game_master', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.TextField(blank=True, default='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('use_status', models.CharField(blank=True, default='', max_length=50)),
                ('bonus', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='diceroll',
            name='skill_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, to='api.skill'),
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('stand_type', models.CharField(blank=True, default='', max_length=100)),
                ('stand_image', models.ImageField(blank=True, null=True, upload_to='stand_images/')),
                ('destructive_power', models.CharField(blank=True, default='', max_length=10)),
                ('speed', models.CharField(blank=True, default='', max_length=10)),
                ('range_stat', models.CharField(blank=True, default='', max_length=10)),
                ('stamina', models.CharField(blank=True, default='', max_length=10)),
                ('precision', models.CharField(blank=True, default='', max_length=10)),
                ('development_potential', models.CharField(blank=True, default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('abilities', models.ManyToManyField(blank=True, to='api.ability')),
                ('owner_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stand', to='api.character')),
            ],
        ),
        migrations.CreateModel(
            name='Zanpakuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sealed_form', models.TextField(blank=True, default='')),
                ('spirit_name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='zanpakuto_images/')),
                ('shikai_command', models.CharField(blank=True, default='', max_length=200)),
                ('shikai_description', models.TextField(blank=True, default='')),
                ('bankai_name', models.CharField(blank=True, default='', max_length=100)),
                ('bankai_description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('bankai_abilities', models.ManyToManyField(blank=True, related_name='zanpakuto_bankai', to='api.ability')),
                ('owner_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zanpakuto', to='api.character')),
                ('shikai_abilities', models.ManyToManyField(blank=True, related_name='zanpakuto_shikai', to='api.ability')),
            ],
        ),
    ]
