# Generated by Django 5.2.4 on 2026-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand_ability',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='stand_ability',
            name='stand',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='owner_character',
        ),
        migrations.AddField(
            model_name='ability',
            name='damage_base',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='ability',
            name='use_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='advantage',
            name='status_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='carisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='destreza',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='força',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='inteligência',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='sabedoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='vigor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='type_item',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalitytrait',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalitytrait',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalitytrait',
            name='use_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skills',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skills',
            name='use_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stand',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='stand_image',
            field=models.ImageField(blank=True, null=True, upload_to='stand_images/'),
        ),
        migrations.AddField(
            model_name='stand',
            name='stand_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stand',
            name='destructive_power',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stand',
            name='development_potential',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stand',
            name='precision',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stand',
            name='range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stand',
            name='speed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stand',
            name='stamina',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='equipment',
        ),
        migrations.DeleteModel(
            name='stand_ability',
        ),
        migrations.DeleteModel(
            name='weapon',
        ),
    ]
