# Generated by Codex on 2026-02-04

from django.db import migrations


def create_default_traits(apps, schema_editor):
    PersonalityTrait = apps.get_model('api', 'PersonalityTrait')
    defaults = [
        # Forca
        ('Forte', 'forca', 1),
        ('Brutal', 'forca', 1),
        ('Atleta', 'forca', 1),
        ('Imponente', 'forca', 1),
        # Destreza
        ('Agil', 'destreza', 1),
        ('Acrobata', 'destreza', 1),
        ('Maos Rapidas', 'destreza', 1),
        ('Evasivo', 'destreza', 1),
        # Vigor
        ('Resistente', 'vigor', 1),
        ('Tenaz', 'vigor', 1),
        ('Incansavel', 'vigor', 1),
        ('Endurecido', 'vigor', 1),
        # Inteligencia
        ('Intelectual', 'inteligencia', 1),
        ('Analitico', 'inteligencia', 1),
        ('Estrategico', 'inteligencia', 1),
        ('Inventivo', 'inteligencia', 1),
        # Sabedoria
        ('Observador', 'sabedoria', 1),
        ('Perceptivo', 'sabedoria', 1),
        ('Calmo', 'sabedoria', 1),
        ('Sabio', 'sabedoria', 1),
        # Carisma
        ('Carismatico', 'carisma', 1),
        ('Lider Nato', 'carisma', 1),
        ('Persuasivo', 'carisma', 1),
        ('Sedutor', 'carisma', 1),
        ('Inspirador', 'carisma', 1),
    ]

    for name, use_status, bonus in defaults:
        existing = PersonalityTrait.objects.filter(
            name=name,
            campaign__isnull=True,
        ).first()
        if existing:
            continue
        PersonalityTrait.objects.create(
            name=name,
            use_status=use_status,
            bonus=bonus,
        )


def reverse_default_traits(apps, schema_editor):
    PersonalityTrait = apps.get_model('api', 'PersonalityTrait')
    names = [
        'Forte', 'Brutal', 'Atleta', 'Imponente',
        'Agil', 'Acrobata', 'Maos Rapidas', 'Evasivo',
        'Resistente', 'Tenaz', 'Incansavel', 'Endurecido',
        'Intelectual', 'Analitico', 'Estrategico', 'Inventivo',
        'Observador', 'Perceptivo', 'Calmo', 'Sabio',
        'Carismatico', 'Lider Nato', 'Persuasivo', 'Sedutor', 'Inspirador',
    ]
    PersonalityTrait.objects.filter(name__in=names, campaign__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_characternote_author_characternote_is_master_note_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_traits, reverse_default_traits),
    ]
