# Generated by Django 5.2.4 on 2026-02-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_default_personality_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bankai_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='bankai_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='cursed_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='cursed_energy_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='shikai_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='shikai_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='stand_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='zanpakuto_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
