# Generated by Codex on 2026-02-05

from django.db import migrations


def seed_personality_traits(apps, schema_editor):
    PersonalityTrait = apps.get_model('api', 'PersonalityTrait')

    traits = [
        {
            'name': 'Corajoso',
            'description': 'Ganha bonus em testes de coragem e resistencia.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Medroso',
            'description': 'Ganha bonus ao evitar perigos e recuar.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Forte',
            'description': 'Ganha bonus em testes de forca bruta.',
            'use_status': 'forca',
            'bonus': 1,
        },
        {
            'name': 'Agil',
            'description': 'Ganha bonus em movimentos rapidos e acrobacias.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Inteligente',
            'description': 'Ganha bonus em raciocinio e analise.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Carismatico',
            'description': 'Ganha bonus em interacoes sociais.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Astuto',
            'description': 'Ganha bonus em planos e armadilhas.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Resiliente',
            'description': 'Ganha bonus em resistencia fisica.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Determinado',
            'description': 'Ganha bonus ao manter o foco sob pressao.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Impulsivo',
            'description': 'Ganha bonus em reacoes rapidas.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Calmo',
            'description': 'Ganha bonus em manter a mente fria.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Leal',
            'description': 'Ganha bonus ao inspirar confianca.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Desconfiado',
            'description': 'Ganha bonus ao perceber riscos e mentiras.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Curioso',
            'description': 'Ganha bonus em investigar e explorar.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Teimoso',
            'description': 'Ganha bonus ao resistir a intimidacao.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Honrado',
            'description': 'Ganha bonus ao liderar pelo exemplo.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Furtivo',
            'description': 'Ganha bonus ao agir sem ser notado.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Observador',
            'description': 'Ganha bonus ao notar detalhes.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Visionario',
            'description': 'Ganha bonus em planejamento a longo prazo.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Estrategico',
            'description': 'Ganha bonus em decisoes taticas.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Protetor',
            'description': 'Ganha bonus ao defender aliados.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Agressivo',
            'description': 'Ganha bonus em ataques diretos.',
            'use_status': 'forca',
            'bonus': 1,
        },
        {
            'name': 'Paciente',
            'description': 'Ganha bonus ao esperar o momento certo.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Disciplinado',
            'description': 'Ganha bonus em manter a postura.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Explosivo',
            'description': 'Ganha bonus em golpes de impacto.',
            'use_status': 'forca',
            'bonus': 1,
        },
        {
            'name': 'Empatico',
            'description': 'Ganha bonus ao entender pessoas.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Orgulhoso',
            'description': 'Ganha bonus em impor respeito.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Altruista',
            'description': 'Ganha bonus ao agir pelo grupo.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Ganancioso',
            'description': 'Ganha bonus em negociacoes e barganhas.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Vingativo',
            'description': 'Ganha bonus ao perseguir um alvo.',
            'use_status': 'forca',
            'bonus': 1,
        },
        {
            'name': 'Bondoso',
            'description': 'Ganha bonus ao acalmar conflitos.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Cruel',
            'description': 'Ganha bonus ao intimidar.',
            'use_status': 'forca',
            'bonus': 1,
        },
        {
            'name': 'Sensato',
            'description': 'Ganha bonus ao tomar decisoes prudentes.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Criativo',
            'description': 'Ganha bonus em solucoes improvisadas.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Audacioso',
            'description': 'Ganha bonus em manobras arriscadas.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Cauteloso',
            'description': 'Ganha bonus ao evitar armadilhas.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Persistente',
            'description': 'Ganha bonus ao insistir em um objetivo.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Solitario',
            'description': 'Ganha bonus ao agir de forma independente.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Lider Nato',
            'description': 'Ganha bonus ao comandar o grupo.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Tatico',
            'description': 'Ganha bonus em combate coordenado.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Mistico',
            'description': 'Ganha bonus em intuicao e fe.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Destemido',
            'description': 'Ganha bonus ao enfrentar ameacas.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Inovador',
            'description': 'Ganha bonus ao criar novas estrategias.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Frio',
            'description': 'Ganha bonus ao manter o controle emocional.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Carinhoso',
            'description': 'Ganha bonus ao confortar aliados.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Manipulador',
            'description': 'Ganha bonus ao direcionar conversas.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Preciso',
            'description': 'Ganha bonus em acoes de precisao.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Reflexos Rapidos',
            'description': 'Ganha bonus ao reagir instantaneamente.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Mira Firme',
            'description': 'Ganha bonus em ataques a distancia.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Robusto',
            'description': 'Ganha bonus ao suportar danos.',
            'use_status': 'vigor',
            'bonus': 1,
        },
    ]

    for trait in traits:
        PersonalityTrait.objects.get_or_create(
            name=trait['name'],
            campaign=None,
            defaults={
                'description': trait['description'],
                'use_status': trait['use_status'],
                'bonus': trait['bonus'],
            },
        )


def unseed_personality_traits(apps, schema_editor):
    PersonalityTrait = apps.get_model('api', 'PersonalityTrait')
    names = [
        'Corajoso', 'Medroso', 'Forte', 'Agil', 'Inteligente', 'Carismatico', 'Astuto',
        'Resiliente', 'Determinado', 'Impulsivo', 'Calmo', 'Leal', 'Desconfiado', 'Curioso',
        'Teimoso', 'Honrado', 'Furtivo', 'Observador', 'Visionario', 'Estrategico',
        'Protetor', 'Agressivo', 'Paciente', 'Disciplinado', 'Explosivo', 'Empatico',
        'Orgulhoso', 'Altruista', 'Ganancioso', 'Vingativo', 'Bondoso', 'Cruel', 'Sensato',
        'Criativo', 'Audacioso', 'Cauteloso', 'Persistente', 'Solitario', 'Lider Nato',
        'Tatico', 'Mistico', 'Destemido', 'Inovador', 'Frio', 'Carinhoso', 'Manipulador',
        'Preciso', 'Reflexos Rapidos', 'Mira Firme', 'Robusto',
    ]
    PersonalityTrait.objects.filter(name__in=names, campaign__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_poweridea'),
    ]

    operations = [
        migrations.RunPython(seed_personality_traits, unseed_personality_traits),
    ]
