# Generated by Codex on 2026-02-05

from django.db import migrations


def seed_more_personality_traits(apps, schema_editor):
    PersonalityTrait = apps.get_model('api', 'PersonalityTrait')

    traits = [
        {
            'name': 'Implacavel',
            'description': 'Ganha bonus ao nao desistir.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Pioneiro',
            'description': 'Ganha bonus em ideias novas.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Inflexivel',
            'description': 'Ganha bonus ao resistir a pressao.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Sereno',
            'description': 'Ganha bonus ao manter a calma.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Veloz',
            'description': 'Ganha bonus em deslocamento rapido.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Calculista',
            'description': 'Ganha bonus em acoes planejadas.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Inquieto',
            'description': 'Ganha bonus em reacoes imediatas.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Brilhante',
            'description': 'Ganha bonus em raciocinio rapido.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Sincero',
            'description': 'Ganha bonus em comunicacao franca.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Resoluto',
            'description': 'Ganha bonus ao tomar decisoes.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Vigilante',
            'description': 'Ganha bonus ao guardar entradas.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Orador',
            'description': 'Ganha bonus ao discursar.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Brutal',
            'description': 'Ganha bonus em ataques fortes.',
            'use_status': 'forca',
            'bonus': 1,
        },
        {
            'name': 'Agarrado',
            'description': 'Ganha bonus em agarrar e segurar.',
            'use_status': 'forca',
            'bonus': 1,
        },
        {
            'name': 'Discreto',
            'description': 'Ganha bonus ao agir sem chamar atencao.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Perceptivo',
            'description': 'Ganha bonus ao notar pequenos sinais.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Idealista',
            'description': 'Ganha bonus ao inspirar esperanca.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Precavido',
            'description': 'Ganha bonus ao evitar riscos.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Tenaz',
            'description': 'Ganha bonus ao resistir a dor.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Rapido',
            'description': 'Ganha bonus em acoes de velocidade.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Inspirador',
            'description': 'Ganha bonus ao motivar aliados.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Organizado',
            'description': 'Ganha bonus ao planejar tarefas.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Racional',
            'description': 'Ganha bonus ao agir com logica.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Firme',
            'description': 'Ganha bonus ao manter postura.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Misericordioso',
            'description': 'Ganha bonus ao evitar violencia.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Flexivel',
            'description': 'Ganha bonus ao se adaptar.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Intrepido',
            'description': 'Ganha bonus ao enfrentar perigos.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Sagaz',
            'description': 'Ganha bonus em leitura de situacoes.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Persistente II',
            'description': 'Ganha bonus ao insistir em metas.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Audaz',
            'description': 'Ganha bonus em acoes ousadas.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Tolerante',
            'description': 'Ganha bonus ao lidar com conflito.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Concentrado',
            'description': 'Ganha bonus ao manter foco.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Prudente',
            'description': 'Ganha bonus ao agir com cautela.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Determinado II',
            'description': 'Ganha bonus ao manter objetivo.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Inventivo',
            'description': 'Ganha bonus ao criar solucoes.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Afiado',
            'description': 'Ganha bonus ao perceber fraquezas.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Habil',
            'description': 'Ganha bonus ao manusear objetos.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Poderoso',
            'description': 'Ganha bonus em demonstracoes de forca.',
            'use_status': 'forca',
            'bonus': 1,
        },
        {
            'name': 'Persuasivo',
            'description': 'Ganha bonus ao convencer.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Persistente III',
            'description': 'Ganha bonus em perseveranca.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Diligente',
            'description': 'Ganha bonus ao trabalhar com cuidado.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Exigente',
            'description': 'Ganha bonus ao impor regras.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Equilibrado',
            'description': 'Ganha bonus em manter estabilidade.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Rapido II',
            'description': 'Ganha bonus em reflexos.',
            'use_status': 'destreza',
            'bonus': 1,
        },
        {
            'name': 'Atento',
            'description': 'Ganha bonus em vigilancia constante.',
            'use_status': 'sabedoria',
            'bonus': 1,
        },
        {
            'name': 'Cativante',
            'description': 'Ganha bonus ao encantar.',
            'use_status': 'carisma',
            'bonus': 1,
        },
        {
            'name': 'Metodico',
            'description': 'Ganha bonus em processos e rotinas.',
            'use_status': 'inteligencia',
            'bonus': 1,
        },
        {
            'name': 'Resiliente II',
            'description': 'Ganha bonus ao suportar fadiga.',
            'use_status': 'vigor',
            'bonus': 1,
        },
        {
            'name': 'Combativo',
            'description': 'Ganha bonus em confronto direto.',
            'use_status': 'forca',
            'bonus': 1,
        },
        {
            'name': 'Veloz II',
            'description': 'Ganha bonus em corridas.',
            'use_status': 'destreza',
            'bonus': 1,
        },
    ]

    for trait in traits:
        PersonalityTrait.objects.get_or_create(
            name=trait['name'],
            campaign=None,
            defaults={
                'description': trait['description'],
                'use_status': trait['use_status'],
                'bonus': trait['bonus'],
            },
        )


def unseed_more_personality_traits(apps, schema_editor):
    PersonalityTrait = apps.get_model('api', 'PersonalityTrait')
    names = [
        'Implacavel', 'Pioneiro', 'Inflexivel', 'Sereno', 'Veloz', 'Calculista',
        'Inquieto', 'Brilhante', 'Sincero', 'Resoluto', 'Vigilante', 'Orador',
        'Brutal', 'Agarrado', 'Discreto', 'Perceptivo', 'Idealista', 'Precavido',
        'Tenaz', 'Rapido', 'Inspirador', 'Organizado', 'Racional', 'Firme',
        'Misericordioso', 'Flexivel', 'Intrepido', 'Sagaz', 'Persistente II',
        'Audaz', 'Tolerante', 'Concentrado', 'Prudente', 'Determinado II',
        'Inventivo', 'Afiado', 'Habil', 'Poderoso', 'Persuasivo', 'Persistente III',
        'Diligente', 'Exigente', 'Equilibrado', 'Rapido II', 'Atento', 'Cativante',
        'Metodico', 'Resiliente II', 'Combativo', 'Veloz II',
    ]
    PersonalityTrait.objects.filter(name__in=names, campaign__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_seed_personality_traits'),
    ]

    operations = [
        migrations.RunPython(seed_more_personality_traits, unseed_more_personality_traits),
    ]
