# Generated by Django 5.2.4 on 2026-02-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_skillidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='map_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_maps/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='map_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='character',
            name='extra_cursed_technique_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='extra_stand_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='extra_zanpakuto_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stand',
            name='owner_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands', to='api.character'),
        ),
        migrations.AlterField(
            model_name='zanpakuto',
            name='owner_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zanpakutos', to='api.character'),
        ),
    ]
