# Generated by Django 5.2.4 on 2026-02-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_item_image_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('common', 'Comum'), ('uncommon', 'Incomum'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Lendário')], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='map_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='session',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='session_maps/'),
        ),
    ]
